services:
  backend:
    build:
      context: ./backend
    container_name: springboot-backend
    ports:
      - "9090:9090"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
        VITE_SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
    container_name: vite-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
